### ISSUE TITLE
when i see FDC1004.cpp, i cannot understand this define"uint8_t SAMPLE_DELAY[] = {11,11,6,3};"

### ISSUE THREAD

**Issue by violet1123** [facebookresearch/FDC1004_CapacitiveSensing#3]
i want to use fdc1004 this chip so i read fdc1004.cpp, i am confused about this code "uint8_t SAMPLE_DELAY[] = {11,11,6,3}", i don't know the meaning of this code then i try to delete this code, luckily it still runs sucessfully! i also read fdc1004 instruction (TI), I still can't find something related to "uint8_t SAMPLE_DELAY[] = {11,11,6,3}".... 
if someone can tell me the meaning of this code? i really confused! thanks!

**Comment by violet1123** [comment]
> i want to use fdc1004 this chip so i read fdc1004.cpp, i am confused about this code "uint8_t SAMPLE_DELAY[] = {11,11,6,3}", i don't know the meaning of this code then i try to delete this code, luckily it still runs sucessfully! i also read fdc1004 instruction (TI), I still can't find something related to "uint8_t SAMPLE_DELAY[] = {11,11,6,3}".... if someone can tell me the meaning of this code? i really confused! thanks!

![fdc10041](https://user-images.githubusercontent.com/52773970/158176247-d852f0d9-57e2-4c10-9299-b7658d112dcc.png)

**Comment by tesshellebrekers** [comment]
SAMPLE_DELAY was only used for testing, you can remove it if you like.
